name: PR Automático da Develop para Main

on:
  push:
    branches:
      - develop

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      - name: Checar se já existe PR aberto
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: `${context.repo.owner}:develop`,
              base: 'main'
            });
            if (prs.data.length > 0) {
              core.setOutput('exists', 'true');
            } else {
              core.setOutput('exists', 'false');
            }
      - name: Criar PR se não existir
        if: steps.pr.outputs.exists == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Merge develop into main',
              head: 'develop',
              base: 'main',
              body: 'PR automático gerado pelo workflow.'
            });
